version : '3'

services:
  lb:
    image: haproxy
    ports: 
      - "8080:8080"
    volumes:
      - ./haproxy:/user/local/etc/haproxy
  nodeapp1:
    image: nodeapp
    environment:
      - APPID=1111  
  nodeapp2:
    image: nodeapp
    environment:
      - APPID=2222
